# Masquerade default client configuration file
# Version 0.2.1, 2024/08/27

# Address of the Masquerade server. Can also be an ipaddress with port
# You need to set this one for the client to work.
server_address = "172.20.0.200:4433"

# The client will create a virtual network interface (TUN) and redirect all network traffic via that device
# Here you can change settings regarding that interface. You only really need to touch them if
# they conflict with existing settings on your system.
interface_address = "10.9.0.2/24"
interface_name = "tun"
interface_gateway = "10.9.0.1"

# If you want the server to only assign a static IP address to your device you can define that
# address here. 
use_static_address = true
static_address = "10.8.1.1/32"
# Needed so the server can identify the client and reserve the address for future use.
client_name = "client"

# The client has multiple threads that read/write from network sockets and handle these messages
# They communicate with each other by using message channels, which can contain a number of messages.
# This option determines the maximum amount of messages in each channel. High numbers may lead
# to instability of the program, while low numbers lead to high packet loss because 
# messages might get dropped when a channel is full.
thread_channel_max = 500

# qlog is a logging format for QUIC connections and can be used for examining different behaviour
# in a connection such as latency, congestion, and more.
# See here for more information: https://quicwg.org/qlog/draft-ietf-quic-qlog-quic-events.html

# If you want qlog files to be created set this to true
create_qlog_file = false
qlog_file_path = "./config/client-logs/"

# The Maximum Transfer Unit for the device interface
# Setting this too high may cause packet fragmentation
# Clients should use the same size
mtu = "1500"

####################################################
#               QUIC Specific Options              #
####################################################

## Different options regarding QUIC
## If you play with these you should know what you are doing

# Congestion algorithm for QUIC to use.
# One of "cubic", "bbr2", "bbr", "reno"

congestion_algorithm = "bbr"

# Max rate for pacing. Set 0 for no limit
max_pacing_rate = 100

# Default = false
disable_active_migration = true

# Enables hystart++ for slowstart
enable_hystart = true

# Turn on the PMTU
discover_pmtu = false

# Delay exponent transport parameter of QUIC ACKs from the server
ack_delay_exponent = 5

# Maximum delay transport parameter of QUIC ACKs from the server
max_ack_delay = 1000

# Maximum idle before the connection gets cut (ms)
# Set this to 0 for infinite timeout
max_idle_timeout = 0