services:
  masquerade_server:
    image: masq_server
    container_name: masquerade_server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./server-config:/config:rw
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    ports:
      - "4433:4433/udp"
    restart: no
    stop_grace_period: 0s
  iperf3:
    container_name: iperf3-client-masq
    image: iperf3_client
    cap_add:
      - NET_ADMIN
    volumes:
      - ./iperf-logs:/iperf:rw
      - ./iperf-tests:/tests:rw
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CURRENT=1
    network_mode: service:masq_server
    depends_on:
      - masq_server